version: '3.8'

services: 
  app:
    build:
      context: .
      dockerfile: Dockerfile

    volumes:
      - ../..:/workspaces:cached
      - ../:/srv/www/Elearnings
    environment:
      - PROJECT_NAME=Elearnings

    ports:
      - "80:80"

    networks:
      - app-network

  db:
    image: mariadb:10.4
    restart: unless-stopped
    volumes:
      - mariadb-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: mariadb
      MYSQL_DATABASE: mariadb
      MYSQL_USER: mariadb
      MYSQL_PASSWORD: mariadb

    networks:
      - app-network

volumes:
  mariadb-data:

networks:
  app-network:
